### ISSUE TITLE
download data

### ISSUE THREAD

**Issue by uf0** [calibro/ee-research#13]
### yt language comparison
download the list of video based on the filters. 
`csv` columns: 

- title
- author
- link
- views
- comments
- likes
- date
- query
- languages: pipe separated (eg: `en|nl`)

### yt clusters
download the list of video based on the filters. 
`csv` columns: 

- title
- link
- cluster
- query
- language

### getty stereotypes
download the list of images based on the filters. 
`csv` columns: 

- query
- stereotype
- link

### getty circulation
remove download button

### tt topics
remove download button from sidebar.
add download button to each cluster page, every line is an hashtag.
`csv` columns: 

- query
- cluster
- number of videos
- hashtag
- language

**Comment by plcdnl** [comment]
- [ ] yt language comparison
- [ ] yt clusters
- [ ] getty stereotypes
- [ ] getty circulation

**tt topics**
remove download button from sidebar.
add download button to each cluster page, every line is an hashtag.
`csv` columns:

- query
- cluster
- number of videos
- hashtag
- language
